//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradesGoneWild.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAlert
    {
        public int AlertID { get; set; }
        public int FKInstrumentID { get; set; }
        public int TargetDirection { get; set; }
        public decimal PriceTarget { get; set; }
        public Nullable<decimal> ClosestPrice { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    
        public virtual StoreInstrument Instrument { get; set; }
    }
}
